#!/usr/bin/env bash
# test-de-brand-output.sh — hermetic proof that a CONSUMER's own workflow brand/name flows through
# to the user-facing doctor + coordinator output, while herdkit's OWN defaults stay byte-unchanged.
#
# Covers external-consumer-audit.md ranked follow-up #7 (Leaks A, E, F): the literal "herdkit"
# brand in `herd doctor`/preflight diagnostics and in the rendered coordinator skill is
# parameterized off the existing config identity (WORKSPACE_NAME, HERD_BRAND override), defaulting
# to the herdkit values.
#
# No network, no claude, no herdr, no gh. Run:  bash tests/test-de-brand-output.sh
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
HERD="$HERE/../bin/herd"
PREFLIGHT="$HERE/../scripts/herd/herd-preflight.sh"
fail(){ echo "FAIL: $1" >&2; exit 1; }

# ── Part 1: the doctor/preflight brand resolves off WORKSPACE_NAME / HERD_BRAND, default herdkit ──
# shellcheck source=/dev/null
. "$PREFLIGHT"   # sourcing is side-effect-free (only defines functions)

# 1a. _herd_brand defaults to the literal herdkit when no identity is set (byte-unchanged default).
( unset WORKSPACE_NAME HERD_BRAND 2>/dev/null || true
  [ "$(_herd_brand)" = "herdkit" ] ) || fail "_herd_brand default is not 'herdkit'"

# 1b. WORKSPACE_NAME (the existing config identity) drives the brand.
( WORKSPACE_NAME="greetd"; [ "$(_herd_brand)" = "greetd" ] ) \
  || fail "_herd_brand did not pick up WORKSPACE_NAME"

# 1c. HERD_BRAND is an explicit override that wins over WORKSPACE_NAME.
( WORKSPACE_NAME="greetd" HERD_BRAND="Acme Flow"; [ "$(_herd_brand)" = "Acme Flow" ] ) \
  || fail "_herd_brand did not honor the HERD_BRAND override"

# 1d. A concrete piece of doctor output (an install hint) shows the CONSUMER's brand, not herdkit.
hint_consumer="$( WORKSPACE_NAME="greetd" _herd_doctor_hint herdr linux )"
case "$hint_consumer" in
  *greetd*) : ;;
  *) fail "doctor herdr hint did not surface the consumer brand: $hint_consumer" ;;
esac
case "$hint_consumer" in
  *herdkit*) fail "doctor herdr hint still leaks the literal 'herdkit' for a consumer" ;;
esac

# 1e. …and the SAME hint with no identity set is byte-unchanged (still says herdkit).
hint_default="$( unset WORKSPACE_NAME HERD_BRAND 2>/dev/null || true; _herd_doctor_hint herdr linux )"
case "$hint_default" in
  *herdkit*) : ;;
  *) fail "doctor herdr hint default no longer says 'herdkit': $hint_default" ;;
esac

# 1f. The preflight herdr-missing message (real user-facing output) carries the consumer brand.
# herd_preflight is already sourced; the herdr-not-found branch uses only shell builtins, so an
# empty PATH (which hides herdr) still runs it without needing an external binary.
missing_msg="$( WORKSPACE_NAME="greetd"; PATH="/var/empty"; herd_preflight 2>&1 || true )"
case "$missing_msg" in
  *"greetd lanes drive"*) : ;;
  *) fail "preflight herdr-missing message did not surface the consumer brand: $missing_msg" ;;
esac

# ── Part 2: the rendered coordinator skill de-brands for a consumer, unchanged for herdkit ────────
seed_repo() { # $1=dir $2=WORKSPACE_NAME $3=HERD_REPO
  git -C "$1" init -q
  git -C "$1" config user.email t@t.t; git -C "$1" config user.name t
  ( cd "$1" && git commit -q --allow-empty -m init )
  mkdir -p "$1/.herd"
  cat > "$1/.herd/config" <<EOF
HERD_VERSION=1
WORKSPACE_NAME="$2"
PROJECT_ROOT="$1"
DEFAULT_BRANCH="origin/main"
BACKLOG_FILE="BACKLOG.md"
SCRIBE_BACKEND="file"
HERD_REPO="$3"
COORDINATOR_CMD="/coordinator"
EOF
}

# 2a. A consumer render: WORKSPACE_NAME=greetd, HERD_REPO=acme/greet.
C="$(mktemp -d)"; trap 'rm -rf "$C" "${H:-}"' EXIT
seed_repo "$C" "greetd" "acme/greet"
( cd "$C" && bash "$HERD" render >/dev/null ) || fail "herd render failed for the consumer repo"
skill="$C/.claude/commands/coordinator.md"
[ -f "$skill" ] || fail "consumer render did not produce a coordinator skill"

# rendering contract intact: no leftover {{TOKENS}}.
grep -q '{{' "$skill" && fail "consumer skill has unrendered {{tokens}}" || true

# the GENERATED-BY-herdkit do-not-hand-edit header is PRESERVED verbatim (rendering contract).
grep -q "GENERATED BY herdkit — DO NOT HAND-EDIT" "$skill" \
  || fail "consumer skill lost the GENERATED-BY-herdkit header"

# the consumer's brand shows through in the coordinator identity.
grep -q "greetd coordinator" "$skill" || fail "consumer skill missing 'greetd coordinator' identity"

# the engine-bug escalation names the consumer's OWN HERD_REPO, not the herdkit author's repo.
grep -q "acme/greet" "$skill" || fail "consumer skill did not render HERD_REPO=acme/greet"

# de-brand: outside the preserved generated banner, no literal 'herdkit' brand leaks into the BRANDABLE
# coordinator prose. Two surfaces name the engine "herdkit" for reasons that are NOT a consumer-brand
# leak, and are pinned OUT here so this scan is deterministic + hermetic (HERD-66):
#   • the engine INSTALL PATH — {{SCRIPTS_DIR}}/{{PROJECT_ROOT}} render to absolute paths under the
#     herdkit checkout dir (here a worktree beneath …/herdkit-trees/), so the literal "herdkit" is a
#     path artifact of WHERE the engine lives, identical for every consumer. Neutralized below.
#   • the {{CAPABILITIES}} engine catalog (header "## Herdkit capabilities …") — brand-INDEPENDENT
#     engine docs that name the herd/herdkit tool itself (this index was added AFTER this test; it is
#     byte-identical in a consumer's render and herdkit's own). Excised as a whole block below.
# What remains is the brandable prose: a genuine un-parameterized "herdkit" there still reds. The scan
# is PIPE-FREE on purpose — the old `grep -v … | grep -q herdkit` under `set -o pipefail` let grep -q
# short-circuit and SIGPIPE the upstream grep, whose 141 exit the pipeline then masked, so a real leak
# passed nondeterministically (worse under concurrent-engine scheduling jitter). awk reads the file
# directly and `case` is a builtin, so there is no pipe and no race.
engine_root="$(cd "$HERE/.." && pwd)"
brandable="$(awk '
  /GENERATED BY herdkit/            { next }        # drop the preserved generated banner
  /^## Herdkit capabilities/        { skip=1; next } # enter the engine capability catalog …
  skip && /^## /                    { skip=0 }       # … until the next top-level (## ) section
  !skip
' "$skill")"
brandable="${brandable//$engine_root/<HERD_HOME>}"   # neutralize the engine install-path artifact
case "$brandable" in
  *herdkit*) fail "consumer coordinator body still leaks the literal 'herdkit' brand" ;;
esac

# 2b. herdkit's OWN render (WORKSPACE_NAME=herdkit) is unchanged: identity + banner still herdkit.
H="$(mktemp -d)"
seed_repo "$H" "herdkit" "briankeegan1/herdkit"
( cd "$H" && bash "$HERD" render >/dev/null ) || fail "herd render failed for the herdkit repo"
hskill="$H/.claude/commands/coordinator.md"
grep -q "herdkit coordinator" "$hskill" || fail "herdkit skill lost its 'herdkit coordinator' identity"
grep -q "GENERATED BY herdkit — DO NOT HAND-EDIT" "$hskill" \
  || fail "herdkit skill lost the GENERATED-BY-herdkit header"
grep -q "briankeegan1/herdkit" "$hskill" || fail "herdkit skill did not render its own HERD_REPO"

# ── Part 3: the driver surface (Leak F) is VISIBLE + SINGLE-SOURCED in the rendered skill ─────────
# Phase 1 of driver-abstraction: the herdr+Claude Code control incantations are consolidated into one
# "Driver commands" reference section and every driver use is tagged with a greppable DRIVER: marker.
# This is a factoring restructure — rendered behavior is unchanged — so the lint asserts the surface
# is present and grep-discoverable, not that any command text changed. Checked on BOTH renders
# (brand-independent), so a consumer skill carries the same driver map as herdkit's own.
for s in "$skill" "$hskill"; do
  # 3a. the single-source reference section rendered.
  grep -q "## Driver commands (herdr + Claude Code)" "$s" \
    || fail "skill lost the 'Driver commands (herdr + Claude Code)' reference section: $s"
  # 3b. every driver capability the skill binds is tagged DRIVER:<capability> and grep-discoverable.
  for cap in list-agents focus-agent send-text switch-model; do
    grep -q "DRIVER:$cap" "$s" || fail "driver surface missing DRIVER:$cap marker in $s"
  done
  # 3c. the phase-2 swap point is pointed at from the rendered skill (surface is documented, not lost).
  grep -q "docs/driver-abstraction.md" "$s" \
    || fail "skill does not reference docs/driver-abstraction.md (phase-2 design): $s"
done

echo "ALL PASS"
