#!/usr/bin/env bash
# test-cli.sh — hermetic test of `herd` CLI init/render/upgrade against a TEMP project repo.
# No network, no claude, no herdr. Run:  bash tests/test-cli.sh
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
HERD="$HERE/../bin/herd"

T="$(mktemp -d)"; trap 'rm -rf "$T"' EXIT
fail(){ echo "FAIL: $1" >&2; exit 1; }

git -C "$T" init -q
git -C "$T" config user.email t@t.t; git -C "$T" config user.name t
( cd "$T" && git commit -q --allow-empty -m init )

# 1. init non-interactively (defaults applied via HERD_NONINTERACTIVE).
( cd "$T" && HERD_NONINTERACTIVE=1 HERD_SKIP_DOCTOR=1 bash "$HERD" init >/dev/null ) || fail "herd init failed"
[ -f "$T/.herd/config" ] || fail "init did not write .herd/config"
[ -f "$T/.claude/commands/coordinator.md" ] || fail "init did not render the coordinator skill"
[ -f "$T/BACKLOG.md" ] || fail "init did not seed BACKLOG.md"

# 2. config carries expected keys + version.
grep -qE '^HERD_VERSION=1$'        "$T/.herd/config" || fail "config missing HERD_VERSION"
grep -qE '^SCRIBE_BACKEND="file"$' "$T/.herd/config" || fail "config missing SCRIBE_BACKEND=file"
grep -qE '^WATCHER_AUTOMERGE='     "$T/.herd/config" || fail "config missing WATCHER_AUTOMERGE"

# 3. rendered skill has the project name + the scripts dir + no leftover tokens.
grep -q "coordinator" "$T/.claude/commands/coordinator.md" || fail "skill missing 'coordinator'"
grep -q "scripts/herd" "$T/.claude/commands/coordinator.md" || fail "skill SCRIPTS_DIR not rendered"
grep -q '{{' "$T/.claude/commands/coordinator.md" && fail "skill has unrendered {{tokens}}" || true
# Generated banner present.
grep -q "GENERATED BY herdkit" "$T/.claude/commands/coordinator.md" || fail "skill missing generated banner"

# 4. render is idempotent (re-render produces an identical file).
cp "$T/.claude/commands/coordinator.md" "$T/skill.before"
( cd "$T" && bash "$HERD" render >/dev/null ) || fail "herd render failed"
diff -q "$T/skill.before" "$T/.claude/commands/coordinator.md" >/dev/null || fail "render not idempotent"

# 5. upgrade keeps the config answers + re-renders.
( cd "$T" && bash "$HERD" upgrade >/dev/null ) || fail "herd upgrade failed"
grep -qE '^HERD_VERSION=1$' "$T/.herd/config" || fail "upgrade clobbered HERD_VERSION"

echo "ALL PASS"
