#!/usr/bin/env bash
# test-py-driver.sh — GOLDEN PARITY tests for the P3d driver-table dispatch port (HERD-317, HERD-300).
#
# P3d ports the PURE, runtime-portable core of the bash driver shim (scripts/herd/driver.sh) to
# stdlib Python (pysrc/herd/driver.py): the .driver-table reader (herd_driver_agent_value), the
# runtime resolver (herd_driver_agent_runtime), the usage-limit-pattern reader
# (herd_driver_agent_limit_pattern), and the runtime-qualified MODEL-ref resolver (herd_model_resolve
# / herd_model_for_spawn / herd_model_driver_for). The bash shim keeps its implementation UNCHANGED —
# this test proves the two agree, read-for-read, on identical inputs. (The dispatch guarantee the port
# adds on top — binary-probe-before-dispatch → DriverUnavailable, and the @degrade→typed-Degraded
# fail-safe — is python-only behavior, unit-tested in tests/test_driver_dispatch.py, run at the end.)
#
# ONE ARGV, TWO IMPLEMENTATIONS, ONE PROCESS EACH (the test-py-decisions.sh idiom):
#   • BASH  — a harness sources scripts/herd/driver.sh ONCE (it defines functions only; sourcing has
#     no side effects), then reads every case from stdin, sets HERD_DRIVER for that case, and calls
#     the REAL functions. No copy of the bash logic lives here, so it cannot drift.
#   • PYTHON — `python3 -m herd.driver --batch` reads the SAME case stream in one process.
# Both emit one line per case; we diff the two streams.
#
# DYNAMIC DISCOVERY (HERD-295 spirit): the cases are generated by ENUMERATING every shipped
# templates/drivers/*.driver at runtime and every DRIVER_AGENT_* key each file actually binds — no
# hardcoded driver or key list — so a sixth driver (or a new binding) is auto-covered with no edit here.
#
# HERD_DRIVERS_DIR pins both implementations at the committed table regardless of cwd. Fully hermetic +
# stdlib-only (no panes/gh/network/HOME; python3 stdlib only — the P1 packaging rule).
# Run:  bash tests/test-py-driver.sh
set -uo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
REPO="$(cd "$HERE/.." && pwd)"
export HERD_DRIVERS_DIR="$REPO/templates/drivers"

command -v python3 >/dev/null 2>&1 || { echo "FAIL: python3 required" >&2; exit 1; }
[ -f "$REPO/scripts/herd/driver.sh" ]  || { echo "FAIL: scripts/herd/driver.sh missing" >&2; exit 1; }
[ -f "$REPO/pysrc/herd/driver.py" ]    || { echo "FAIL: pysrc/herd/driver.py missing" >&2; exit 1; }
[ -d "$HERD_DRIVERS_DIR" ]             || { echo "FAIL: drivers dir missing" >&2; exit 1; }

T="$(mktemp -d)"; trap 'rm -rf "$T"' EXIT
fail() { echo "FAIL: $1" >&2; exit 1; }

SEP=$'\x1f'                 # non-whitespace field sep: preserves empty fields
CASES="$T/cases"; : > "$CASES"
ncases=0

# emit <driver|@U> <verb> [args...]  — append one case line.  @U ⇒ HERD_DRIVER unset (default driver).
emit() {
  local line="$1$SEP$2"; shift 2
  local a; for a in "$@"; do line="$line$SEP$a"; done
  printf '%s\n' "$line" >> "$CASES"
  ncases=$((ncases + 1))
}

# ── the BASH harness: source driver.sh's real functions ONCE, then stream cases from stdin ──────
HARNESS="$T/harness.sh"
cat > "$HARNESS" <<HSH
set -uo pipefail
export HERD_DRIVERS_DIR="$HERD_DRIVERS_DIR"
source "$REPO/scripts/herd/driver.sh" >/dev/null 2>&1 || { echo "SOURCE_FAIL" >&2; exit 3; }
SEP=\$'\x1f'
while IFS="\$SEP" read -ra F; do
  [ "\${#F[@]}" -ge 2 ] || continue
  if [ "\${F[0]}" = @U ]; then unset HERD_DRIVER; else export HERD_DRIVER="\${F[0]}"; fi
  verb="\${F[1]}"; args=( "\${F[@]:2}" )
  # bash-3.2-safe empty-array expansion (\${a[@]} alone trips set -u when the array is empty).
  A=( \${args[@]+"\${args[@]}"} )
  out=""
  case "\$verb" in
    agent-value)      out="\$(herd_driver_agent_value \${A[@]+"\${A[@]}"})" ;;
    agent-runtime)    out="\$(herd_driver_agent_runtime)" ;;
    limit-pattern)    out="\$(herd_driver_agent_limit_pattern \${A[@]+"\${A[@]}"})" ;;
    driver-for)       out="\$(herd_model_driver_for \${A[@]+"\${A[@]}"} 2>/dev/null || true)" ;;
    for-spawn)        out="\$(herd_model_for_spawn \${A[@]+"\${A[@]}"} 2>/dev/null)" || out="@ERR" ;;
    resolve)          out="\$(herd_model_resolve \${A[@]+"\${A[@]}"} 2>/dev/null)" || out="@ERR" ;;
    known)            if herd_driver_known \${A[@]+"\${A[@]}"}; then out=yes; else out=no; fi ;;
    resolved-runtime) rt="\$(herd_driver_agent_runtime)"; [ -n "\$rt" ] || rt=claude; out="\$rt" ;;
    *) echo "BAD_VERB \$verb" >&2; exit 4 ;;
  esac
  printf '%s\n' "\$out"
done
HSH

# ── (1) DYNAMIC: every shipped driver × every DRIVER_AGENT_* key it binds, plus runtime/limit ────
DRIVERS=()
for f in "$HERD_DRIVERS_DIR"/*.driver; do
  [ -e "$f" ] || continue
  b="${f##*/}"; DRIVERS+=("${b%.driver}")
done
[ "${#DRIVERS[@]}" -gt 0 ] || fail "no *.driver files discovered under $HERD_DRIVERS_DIR"

for drv in "${DRIVERS[@]}"; do
  emit "$drv" agent-runtime
  emit "$drv" resolved-runtime
  emit "$drv" limit-pattern
  emit "$drv" limit-pattern "$drv"
  emit "$drv" known "$drv"
  # every DRIVER_AGENT_* key this file actually binds (dynamic — no hardcoded key list)
  while IFS= read -r key; do
    [ -n "$key" ] || continue
    emit "$drv" agent-value "$key"
  done < <(grep -oE '^DRIVER_AGENT_[A-Za-z0-9_]+=' "$HERD_DRIVERS_DIR/$drv.driver" | sed 's/=$//' | sort -u)
  # a couple of MUX keys + a default-fallback probe
  emit "$drv" agent-value DRIVER_LIST_AGENTS
  emit "$drv" agent-value NO_SUCH_KEY_XYZ default-here
done

# a case with HERD_DRIVER unset (default driver resolves via herd_driver_name)
emit @U agent-runtime
emit @U agent-value DRIVER_AGENT_ONESHOT_EXEC
emit @U known no-such-driver

# ── (2) MODEL-ref resolver — bare / qualified / unknown / empty-model, under several active drivers ─
REFS=("" "bare-model" "llama3:8b")
for drv in "${DRIVERS[@]}"; do
  REFS+=("$drv:some-model" "$drv:" "$drv:a:b:c")
done
REFS+=("nope:x" "no-such-driver:m" ":leadingcolon")

for active in "${DRIVERS[@]}" @U; do
  for ref in "${REFS[@]}"; do
    emit "$active" resolve "$ref"
    emit "$active" driver-for "$ref"
    emit "$active" for-spawn "$ref"
  done
done

# ── run BOTH implementations over the whole case stream, ONE process each, and diff ─────────────
BOUT="$T/bash.out"; POUT="$T/py.out"
bash "$HARNESS" < "$CASES" > "$BOUT" 2>"$T/bash.err" || fail "bash harness errored: $(cat "$T/bash.err")"
PYTHONPATH="$REPO/pysrc" python3 -m herd.driver --batch < "$CASES" > "$POUT" 2>"$T/py.err" \
  || fail "python batch errored: $(cat "$T/py.err")"

bl="$(wc -l < "$BOUT" | tr -d ' ')"; pl="$(wc -l < "$POUT" | tr -d ' ')"
[ "$bl" = "$ncases" ] || fail "bash produced $bl lines, expected $ncases cases"
[ "$pl" = "$ncases" ] || fail "python produced $pl lines, expected $ncases cases"

if ! cmp -s "$BOUT" "$POUT"; then
  ln="$(diff "$BOUT" "$POUT" | grep -m1 -oE '^[0-9]+' || echo '?')"
  echo "---- first divergence at output line $ln ----" >&2
  echo "case : $(sed -n "${ln}p" "$CASES" | tr "$SEP" ' ')" >&2
  echo "bash : $(sed -n "${ln}p" "$BOUT")" >&2
  echo "py   : $(sed -n "${ln}p" "$POUT")" >&2
  fail "driver-table parity: bash and python disagree ($ncases cases)"
fi

# ── (3) stdlib unit tests: parse-as-data, @degrade→Degraded, probe→DriverUnavailable, stub e2e ──
PYTHONPATH="$REPO/pysrc" python3 "$HERE/test_driver_dispatch.py" >/dev/null 2>&1 \
  || fail "stdlib dispatch unit tests failed (run: PYTHONPATH=pysrc python3 tests/test_driver_dispatch.py)"

echo "ALL PASS ($ncases parity cases + stdlib dispatch units)"
