#!/usr/bin/env bash
# test-cli-reload.sh — hermetic tests for `herd reload`.
#
# Design principles (mirrors test-watcher-checks.sh / test-merge-policy.sh):
#   • pgrep is STUBBED on PATH — returns only $FAKE_STRAY_PIDS (colon-separated list).
#     This prevents the real pgrep from finding actual agent-watch.sh processes in
#     other workspaces (production or other worktrees), making every test independent of
#     the ambient process table.
#   • herdr is STUBBED (exits 1) — forces the background-fallback path without a real
#     herdr instance. Tests 11+ prepend a RICH herdr stub (file-backed simulation of the
#     workspace/tab/pane/agent JSON API) to exercise the herdr control-room path — still
#     hermetic: pane run only records the command, no process is ever spawned.
#   • HERD_RELOAD_SKIP_LAUNCH=1 suppresses the background watcher launch so no
#     persistent herd-watch.sh / agent-watch.sh processes are spawned.
#   • HERD_RELOAD_SIGTERM_POLLS=3 (3×0.2s) shortens the SIGTERM wait in tests that
#     kill live processes, so we do not wait the full 10s production window.
#   • Kill tests use real, innocuous sleep processes as fake watchers — never the real
#     agent-watch.sh; stray-guard tests control the cwd of those processes.
#
# Run:  bash tests/test-cli-reload.sh
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
HERD="$HERE/../bin/herd"

T="$(mktemp -d)"; trap 'rm -rf "$T"' EXIT
fail(){ echo "FAIL: $1" >&2; exit 1; }
pass=0
ok(){ pass=$((pass+1)); }

# ── Stub pgrep and herdr on PATH ─────────────────────────────────────────────
# pgrep stub: echoes each colon-separated PID in $FAKE_STRAY_PIDS.  All other args
# (e.g. -f "agent-watch.sh") are ignored so the real process table is never consulted.
# This is the key safety property: cmd_reload never sees production agent-watch PIDs.
BIN="$T/bin"; mkdir -p "$BIN"
cat > "$BIN/pgrep" <<'STUB'
#!/usr/bin/env bash
IFS=':' read -ra pids <<< "${FAKE_STRAY_PIDS:-}"
for p in "${pids[@]}"; do [ -n "$p" ] && printf '%s\n' "$p"; done
exit 0
STUB
chmod +x "$BIN/pgrep"

# herdr stub: always exits 1 — forces the background-fallback path.
printf '#!/usr/bin/env bash\nexit 1\n' > "$BIN/herdr"; chmod +x "$BIN/herdr"

export PATH="$BIN:$PATH"

# _make_project ROOT WORKSPACE [extra config lines...]
# PROJECT_ROOT is set to the canonical (realpath) of ROOT so lsof cwd comparisons
# match on macOS where /var/folders is a symlink to /private/var/folders.
_make_project() {
  local r="$1" ws="$2"; shift 2
  local r_real; r_real="$(cd "$r" && pwd -P)"
  git -C "$r" init -q
  git -C "$r" config user.email t@t.t; git -C "$r" config user.name t
  ( cd "$r" && git commit -q --allow-empty -m init )
  mkdir -p "$r/.herd" "$r/trees"
  cat > "$r/.herd/config" <<CFG
HERD_VERSION=1
PROJECT_ROOT="$r_real"
WORKTREES_DIR="$r_real/trees"
DEFAULT_BRANCH="origin/main"
WORKSPACE_NAME="$ws"
BACKLOG_FILE="BACKLOG.md"
SCRIBE_BACKEND="file"
WATCHER_AUTOMERGE="true"
CFG
  for line in "$@"; do printf '%s\n' "$line" >> "$r/.herd/config"; done
}

# ── 1. reload renders the coordinator skill ───────────────────────────────────
P="$T/p1"; mkdir "$P"
_make_project "$P" "reloadtest"
( cd "$P" && HERD_RELOAD_SKIP_LAUNCH=1 bash "$HERD" reload >/dev/null 2>&1 ) \
  || fail "reload failed (basic run)"
[ -f "$P/.claude/commands/coordinator.md" ] || fail "reload did not render coordinator skill"
grep -q "GENERATED BY herdkit" "$P/.claude/commands/coordinator.md" \
  || fail "rendered skill missing generated banner"
grep -q '{{' "$P/.claude/commands/coordinator.md" \
  && fail "rendered skill has unrendered {{tokens}}" || true
ok

# ── 2a. MERGE_POLICY=auto is printed ─────────────────────────────────────────
P="$T/p2a"; mkdir "$P"
_make_project "$P" "reloadtest" 'MERGE_POLICY="auto"'
out="$( cd "$P" && HERD_RELOAD_SKIP_LAUNCH=1 bash "$HERD" reload 2>&1 )"
printf '%s' "$out" | grep -q "MERGE_POLICY:" || fail "output missing MERGE_POLICY line"
printf '%s' "$out" | grep -q "auto"          || fail "MERGE_POLICY should be 'auto'"
ok

# ── 2b. MERGE_POLICY=approve ──────────────────────────────────────────────────
P="$T/p2b"; mkdir "$P"
_make_project "$P" "reloadtest" 'MERGE_POLICY="approve"'
out="$( cd "$P" && HERD_RELOAD_SKIP_LAUNCH=1 bash "$HERD" reload 2>&1 )"
printf '%s' "$out" | grep -q "approve" || fail "MERGE_POLICY should be 'approve'"
ok

# ── 2c. MERGE_POLICY=observe ──────────────────────────────────────────────────
P="$T/p2c"; mkdir "$P"
_make_project "$P" "reloadtest" 'MERGE_POLICY="observe"'
out="$( cd "$P" && HERD_RELOAD_SKIP_LAUNCH=1 bash "$HERD" reload 2>&1 )"
printf '%s' "$out" | grep -q "observe" || fail "MERGE_POLICY should be 'observe'"
ok

# ── 2d. WATCHER_AUTOMERGE=false → approve when MERGE_POLICY unset ────────────
P="$T/p2d"; mkdir "$P"
_make_project "$P" "reloadtest" 'WATCHER_AUTOMERGE="false"'
out="$( cd "$P" && HERD_RELOAD_SKIP_LAUNCH=1 bash "$HERD" reload 2>&1 )"
printf '%s' "$out" | grep -q "approve" || fail "WATCHER_AUTOMERGE=false should derive approve"
ok

# ── 2e. Default (WATCHER_AUTOMERGE=true, no MERGE_POLICY) → auto ─────────────
P="$T/p2e"; mkdir "$P"
_make_project "$P" "reloadtest"
out="$( cd "$P" && HERD_RELOAD_SKIP_LAUNCH=1 bash "$HERD" reload 2>&1 )"
printf '%s' "$out" | grep -q "auto" || fail "default WATCHER_AUTOMERGE=true should derive auto"
ok

# ── 3. reload removes lockfile with a non-existent PID ───────────────────────
P="$T/p3"; mkdir "$P"
_make_project "$P" "reloadtest"
lockfile="$P/trees/.watcher-reloadtest.pid"
printf '%s\n' "99999999" > "$lockfile"   # almost certainly a non-existent PID
( cd "$P" && HERD_RELOAD_SKIP_LAUNCH=1 bash "$HERD" reload >/dev/null 2>&1 ) \
  || fail "reload failed with dead-PID lockfile"
[ -f "$lockfile" ] && fail "reload did not remove the lockfile" || true
ok

# ── 4. reload kills a live process recorded in the lockfile (SIGTERM path) ────
# HERD_RELOAD_SIGTERM_POLLS=3 (3×0.2s = 0.6s) so we do not wait the full 10s.
P="$T/p4"; mkdir "$P"
_make_project "$P" "reloadtest"
lockfile="$P/trees/.watcher-reloadtest.pid"
sleep 999 &
FAKEPID=$!
printf '%s\n' "$FAKEPID" > "$lockfile"
( cd "$P" && HERD_RELOAD_SIGTERM_POLLS=3 HERD_RELOAD_SKIP_LAUNCH=1 bash "$HERD" reload >/dev/null 2>&1 ) \
  || { kill "$FAKEPID" 2>/dev/null || true; fail "reload failed when a live PID was in lockfile"; }
sleep 0.3
kill -0 "$FAKEPID" 2>/dev/null \
  && { kill "$FAKEPID" 2>/dev/null || true; fail "reload did not kill the fake watcher (PID $FAKEPID)"; } \
  || true
[ -f "$lockfile" ] && fail "reload did not remove the lockfile after killing watcher" || true
ok

# ── 5. reload notes no running watcher when lockfile is absent ───────────────
P="$T/p5"; mkdir "$P"
_make_project "$P" "reloadtest"
out="$( cd "$P" && HERD_RELOAD_SKIP_LAUNCH=1 bash "$HERD" reload 2>&1 )"
printf '%s' "$out" | grep -qi "no running watcher\|not found" \
  || fail "reload should note no running watcher when lockfile is absent"
ok

# ── 6. reload fails clearly with no .herd/config ─────────────────────────────
P="$T/p6"; mkdir "$P"
git -C "$P" init -q; git -C "$P" config user.email t@t.t; git -C "$P" config user.name t
( cd "$P" && git commit -q --allow-empty -m init )
out="$( cd "$P" && HERD_RELOAD_SKIP_LAUNCH=1 bash "$HERD" reload 2>&1 || true )"
printf '%s' "$out" | grep -qi "herd init\|no .herd/config" \
  || fail "reload should report missing .herd/config clearly"
ok

# ── 7. Stray guard — OUR workspace: stray cwd == PROJECT_ROOT → killed ───────
# A process whose current working directory IS our PROJECT_ROOT is treated as a stray
# watcher belonging to this workspace and must be killed.
P="$T/p7"; mkdir "$P"
_make_project "$P" "reloadtest"
P_REAL="$(cd "$P" && pwd -P)"
# Start a sleep under the canonical PROJECT_ROOT so lsof -d cwd reports P_REAL.
( cd "$P_REAL" && exec sleep 9999 ) &
STRAY_PID=$!
# pgrep stub will return STRAY_PID (as a stray not in the lockfile).
( cd "$P" && FAKE_STRAY_PIDS="$STRAY_PID" HERD_RELOAD_SKIP_LAUNCH=1 bash "$HERD" reload >/dev/null 2>&1 ) \
  || { kill "$STRAY_PID" 2>/dev/null || true; fail "reload failed (stray-our test)"; }
sleep 0.3
kill -0 "$STRAY_PID" 2>/dev/null \
  && { kill "$STRAY_PID" 2>/dev/null || true; fail "stray in OUR workspace was not killed"; } \
  || true
ok

# ── 8. Stray guard — OTHER workspace: stray cwd != PROJECT_ROOT → NOT killed ─
# A process whose cwd is a DIFFERENT directory must never be killed — this is the
# guard against cmd_reload touching another workspace's watcher.
P="$T/p8"; mkdir "$P"
_make_project "$P" "reloadtest"
OTHER="$T/other_project"; mkdir -p "$OTHER"
OTHER_REAL="$(cd "$OTHER" && pwd -P)"
# Start a sleep from OTHER_REAL (simulates another workspace's watcher).
( cd "$OTHER_REAL" && exec sleep 9999 ) &
OTHER_PID=$!
( cd "$P" && FAKE_STRAY_PIDS="$OTHER_PID" HERD_RELOAD_SKIP_LAUNCH=1 bash "$HERD" reload >/dev/null 2>&1 ) \
  || { kill "$OTHER_PID" 2>/dev/null || true; fail "reload failed (stray-other test)"; }
sleep 0.2
if kill -0 "$OTHER_PID" 2>/dev/null; then
  kill "$OTHER_PID" 2>/dev/null || true
  ok   # process survived — guard worked correctly
else
  fail "reload killed a process from another workspace (guard failure)"
fi

# ── 9. SIGKILL escalation: SIGTERM-ignoring process is killed by SIGKILL ──────
# Verifies the bounded-wait → SIGKILL path: a process that traps and ignores SIGTERM
# (as a watcher mid-review/merge would via deferred bash SIGTERM) must still be stopped.
# HERD_RELOAD_SIGTERM_POLLS=3 (0.6s wait) triggers the SIGKILL branch quickly.
P="$T/p9"; mkdir "$P"
_make_project "$P" "reloadtest"
lockfile="$P/trees/.watcher-reloadtest.pid"
# Fake watcher that ignores SIGTERM (simulates watcher blocked in a long child).
( trap '' TERM; sleep 9999 ) &
STUBBORN=$!
printf '%s\n' "$STUBBORN" > "$lockfile"
( cd "$P" && HERD_RELOAD_SIGTERM_POLLS=3 HERD_RELOAD_SKIP_LAUNCH=1 bash "$HERD" reload >/dev/null 2>&1 ) \
  || { kill -9 "$STUBBORN" 2>/dev/null || true; fail "reload failed (SIGKILL escalation test)"; }
sleep 0.3
kill -0 "$STUBBORN" 2>/dev/null \
  && { kill -9 "$STUBBORN" 2>/dev/null || true; fail "SIGTERM-ignoring process was not killed by SIGKILL"; } \
  || true
[ -f "$lockfile" ] && fail "lockfile not removed after SIGKILL" || true
ok

# ── 10. EXIT trap guard: dying old watcher does not delete new watcher's lock ─
# The no-flock EXIT trap in agent-watch.sh guards with [ $(cat lockfile) = $$ ].
# Simulate: old watcher writes its PID, we replace it with a new PID (simulating
# cmd_reload relaunching a new watcher), then kill the old watcher — its EXIT trap
# must see the lockfile no longer contains its own PID and leave it alone.
P="$T/p10"; mkdir "$P"
_make_project "$P" "reloadtest"
lockfile="$P/trees/.watcher-reloadtest.pid"
mkdir -p "$P/trees"
# Old watcher subprocess with the guarded EXIT trap (mirrors agent-watch.sh exactly).
(
  printf '%s\n' "$$" > "$lockfile"
  _watcher_lock_cleanup() {
    [ "$(cat "$lockfile" 2>/dev/null)" = "$$" ] \
      && rm -f "$lockfile" 2>/dev/null || true
  }
  trap '_watcher_lock_cleanup' EXIT
  trap '_watcher_lock_cleanup; exit 1' INT TERM
  sleep 9999
) &
OLD_WATCHER=$!
sleep 0.15   # let it write its PID

# Simulate cmd_reload removing old lock and new watcher writing its PID.
rm -f "$lockfile" 2>/dev/null || true
NEW_PID="77777"
printf '%s\n' "$NEW_PID" > "$lockfile"

# Kill the old watcher — its EXIT trap fires.
kill "$OLD_WATCHER" 2>/dev/null || true
sleep 0.3

# The guarded EXIT trap should have left the lockfile alone (PID mismatch).
[ -f "$lockfile" ] \
  || fail "EXIT trap deleted the new watcher's lockfile (guard missing)"
cur="$(cat "$lockfile" 2>/dev/null || true)"
[ "$cur" = "$NEW_PID" ] \
  || fail "EXIT trap modified the new watcher's lockfile (got '$cur', want '$NEW_PID')"
ok

# Sanity: EXIT trap DOES remove the lock when file still contains the old PID.
rm -f "$lockfile" 2>/dev/null || true
(
  printf '%s\n' "$$" > "$lockfile"
  _watcher_lock_cleanup() {
    [ "$(cat "$lockfile" 2>/dev/null)" = "$$" ] \
      && rm -f "$lockfile" 2>/dev/null || true
  }
  trap '_watcher_lock_cleanup' EXIT
  # Exit naturally — no replacement PID written.
)
[ -f "$lockfile" ] \
  && fail "EXIT trap did not remove lockfile on natural exit (guard too aggressive)" || true
ok

# ═══ herdr control-room path (tests 11+) ═════════════════════════════════════
# Rich herdr stub: a file-backed simulation of the JSON API surface cmd_reload uses.
# State lives under $HERDR_STATE:
#   tabs/<tab_id>            file content = tab label
#   panes/<pane_id>/cmd      last `pane run` command (recorded, NEVER executed)
#   panes/<pane_id>/noshow   marker: process-info never shows cmd (invisible-pane bug sim)
#   neighbors/<pane>.<dir>   neighbor pane id for `pane neighbor`
#   agents.json              canned `agent list` response
#   log                      every invocation, one line, for assertions
# Env: FAKE_WS_LABEL (workspace label), FAKE_RUN_WRITES_LOCK=path:pid (pane run writes
# pid to path — simulates a detached watcher grabbing the lockfile).
RICH="$T/richbin"; mkdir -p "$RICH"
cat > "$RICH/herdr" <<'STUB'
#!/usr/bin/env bash
S="${HERDR_STATE:?}"; mkdir -p "$S/tabs" "$S/panes" "$S/neighbors"
echo "$*" >> "$S/log"
next_id(){ local n=0; [ -f "$S/seq" ] && n="$(cat "$S/seq")"; n=$((n+1)); echo "$n" > "$S/seq"; printf '%s' "$n"; }
case "${1:-} ${2:-}" in
  "workspace list")
    printf '{"result":{"workspaces":[{"workspace_id":"w1","label":"%s"}]}}\n' "${FAKE_WS_LABEL:-}" ;;
  "tab list")
    python3 - "$S" <<'PY'
import sys,os,json
S=sys.argv[1]; d=os.path.join(S,"tabs")
tabs=[{"tab_id":t,"label":open(os.path.join(d,t)).read().strip()} for t in sorted(os.listdir(d))]
print(json.dumps({"result":{"tabs":tabs}}))
PY
    ;;
  "tab create")
    label=""; shift 2
    while [ $# -gt 0 ]; do case "$1" in --label) label="${2:-}"; shift 2 ;; *) shift ;; esac; done
    tid="t$(next_id)"; printf '%s' "$label" > "$S/tabs/$tid"
    pid="p$(next_id)"; mkdir -p "$S/panes/$pid"; printf '%s' "$tid" > "$S/panes/$pid/tab"
    printf '{"result":{"tab":{"tab_id":"%s"},"root_pane":{"pane_id":"%s"}}}\n' "$tid" "$pid" ;;
  "tab close")
    rm -f "$S/tabs/${3:-}"; printf '{"result":{}}\n' ;;
  "agent list")
    if [ -f "$S/agents.json" ]; then cat "$S/agents.json"; else printf '{"result":{"agents":[]}}\n'; fi ;;
  "pane run")
    p="${3:-}"; mkdir -p "$S/panes/$p"; printf '%s' "${4:-}" > "$S/panes/$p/cmd"
    if [ -n "${FAKE_RUN_WRITES_LOCK:-}" ]; then
      printf '%s\n' "${FAKE_RUN_WRITES_LOCK##*:}" > "${FAKE_RUN_WRITES_LOCK%:*}"
    fi
    printf '{"result":{}}\n' ;;
  "pane process-info")
    p="${4:-}"
    if [ ! -d "$S/panes/$p" ]; then printf '{"result":{}}\n'; exit 0; fi
    cmd=""
    [ -f "$S/panes/$p/cmd" ] && [ ! -f "$S/panes/$p/noshow" ] && cmd="$(cat "$S/panes/$p/cmd")"
    if [ -n "$cmd" ]; then
      printf '{"result":{"process_info":{"shell_pid":4242,"foreground_processes":[{"pid":5151,"cmdline":"%s"}]}}}\n' "$cmd"
    else
      printf '{"result":{"process_info":{"shell_pid":4242,"foreground_processes":[]}}}\n'
    fi ;;
  "pane neighbor")
    d="${4:-}"; p="${6:-}"; nb=""
    [ -f "$S/neighbors/$p.$d" ] && nb="$(cat "$S/neighbors/$p.$d")"
    if [ -n "$nb" ]; then
      printf '{"result":{"neighbor":{"pane_id":"%s","neighbor_pane_id":"%s"}}}\n' "$p" "$nb"
    else
      printf '{"result":{"neighbor":{"pane_id":"%s"}}}\n' "$p"
    fi ;;
  "pane split")
    p="p$(next_id)"; mkdir -p "$S/panes/$p"
    printf '{"result":{"pane":{"pane_id":"%s"}}}\n' "$p" ;;
  "pane swap")
    printf '{"result":{}}\n' ;;
  *) printf '{"result":{}}\n' ;;
esac
exit 0
STUB
chmod +x "$RICH/herdr"

# _rich_reload PROJECT STATE [env VAR=VAL ...] — run reload against the rich stub.
# HERD_RELOAD_SKIP_LAUNCH=fallback keeps it hermetic: even if the herdr path fails,
# no real background watcher is ever spawned.
_rich_reload() {
  local proj="$1" state="$2"; shift 2
  ( cd "$proj" && env PATH="$RICH:$PATH" HERDR_STATE="$state" FAKE_WS_LABEL="reloadtest" \
      HERD_RELOAD_SKIP_LAUNCH=fallback HERD_RELOAD_PANE_POLLS=2 HERD_RELOAD_VERIFY_POLLS=2 \
      HERD_RELOAD_LOCKPID_POLLS=1 \
      "$@" bash "$HERD" reload 2>&1 )
}

# _rich_coord_state STATE — coordinator control-room fixture: tab tC labeled as the
# coordinator, agent pane pA, bare backlog pane pL left of it, bare watch pane pW below.
_rich_coord_state() {
  local S="$1"
  mkdir -p "$S/tabs" "$S/panes/pA" "$S/panes/pL" "$S/panes/pW" "$S/neighbors"
  printf 'coordinator-reloadtest' > "$S/tabs/tC"
  printf 'tC' > "$S/panes/pA/tab"
  printf 'pL' > "$S/neighbors/pA.left"
  printf 'pW' > "$S/neighbors/pA.down"
  printf '%s\n' '{"result":{"agents":[{"name":"coordinator-reloadtest","pane_id":"pA","tab_id":"tC","workspace_id":"w1"}]}}' \
    > "$S/agents.json"
}

# ── 11. herdr path, no coordinator → standalone watch + backlog tabs, verified ─
P="$T/p11"; mkdir "$P"
_make_project "$P" "reloadtest"
S="$T/state11"
out="$(_rich_reload "$P" "$S")" || fail "reload failed (herdr standalone path)"
printf '%s' "$out" | grep -q "herdr tab watch-reloadtest" || fail "watcher not placed in a standalone watch tab"
printf '%s' "$out" | grep -q "visible ✓" || fail "watcher visibility not verified/reported"
printf '%s' "$out" | grep -q "tab backlog-reloadtest" || fail "backlog not placed in a standalone tab"
grep -rl "herd-watch.sh" "$S/panes" >/dev/null || fail "no pane received the watch script"
grep -rl "backlog-view.sh" "$S/panes" >/dev/null || fail "no pane received backlog-view.sh"
ok

# ── 12. coordinator layout: watch below + backlog left reused; coordinator untouched ─
P="$T/p12"; mkdir "$P"
_make_project "$P" "reloadtest"
S="$T/state12"; _rich_coord_state "$S"
out="$(_rich_reload "$P" "$S")" || fail "reload failed (coordinator layout)"
grep -q "herd-watch.sh" "$S/panes/pW/cmd" 2>/dev/null || fail "watch script not run in the pane below the coordinator"
grep -q "backlog-view.sh" "$S/panes/pL/cmd" 2>/dev/null || fail "backlog-view not run in the pane left of the coordinator"
printf '%s' "$out" | grep -q "pane below coordinator" || fail "output missing 'pane below coordinator'"
printf '%s' "$out" | grep -q "visible ✓" || fail "watcher visibility not reported (coordinator layout)"
grep -q "tab close tC" "$S/log" && fail "reload CLOSED the coordinator tab (must never happen)" || true
grep -q "pane split" "$S/log" && fail "reload split a pane when both panes were reusable" || true
[ -f "$S/tabs/tC" ] || fail "coordinator tab is gone from state"
ok

# ── 13. live backlog pane is left completely untouched ────────────────────────
P="$T/p13"; mkdir "$P"
_make_project "$P" "reloadtest"
S="$T/state13"; _rich_coord_state "$S"
printf 'bash /somewhere/backlog-view.sh' > "$S/panes/pL/cmd"   # already live
out="$(_rich_reload "$P" "$S")" || fail "reload failed (live backlog test)"
printf '%s' "$out" | grep -q "already live ✓" || fail "live backlog pane not reported as already live"
grep -q "pane run pL" "$S/log" && fail "reload re-ran a command in the LIVE backlog pane" || true
ok

# ── 14. invisible-watcher bug: run lands detached → retry once, then LOUD report ─
# The watch pane never shows the command (noshow), but each pane run "starts" a detached
# watcher that grabs the lockfile (FAKE_RUN_WRITES_LOCK with a live PID). Reload must
# retry the pane run once, detect the running-but-invisible watcher via the lockfile,
# and report it loudly — never a silent zombie pane, never a duplicate spawn.
P="$T/p14"; mkdir "$P"
_make_project "$P" "reloadtest"
S="$T/state14"; _rich_coord_state "$S"
touch "$S/panes/pW/noshow"
sleep 999 & ZPID=$!
lockfile="$P/trees/.watcher-reloadtest.pid"
out="$(_rich_reload "$P" "$S" FAKE_RUN_WRITES_LOCK="$lockfile:$ZPID")" \
  || { kill "$ZPID" 2>/dev/null || true; fail "reload failed (invisible-watcher test)"; }
runs="$(grep -c "pane run pW" "$S/log" || true)"
[ "$runs" -eq 2 ] || { kill "$ZPID" 2>/dev/null || true; fail "expected exactly 2 pane run attempts (retry once), got $runs"; }
printf '%s' "$out" | grep -q "RUNNING but NOT visible" \
  || { kill "$ZPID" 2>/dev/null || true; fail "invisible watcher not reported loudly"; }
printf '%s' "$out" | grep -q "DETACHED" \
  || { kill "$ZPID" 2>/dev/null || true; fail "summary missing DETACHED watcher state"; }
[ "$(cat "$lockfile" 2>/dev/null)" = "$ZPID" ] \
  || { kill "$ZPID" 2>/dev/null || true; fail "detached watcher's lockfile was clobbered"; }
kill "$ZPID" 2>/dev/null || true
ok

# ── 15. missing backlog pane → split coordinator + swap into the LEFT slot ────
P="$T/p15"; mkdir "$P"
_make_project "$P" "reloadtest"
S="$T/state15"; _rich_coord_state "$S"
rm -f "$S/neighbors/pA.left"   # user closed the backlog pane
out="$(_rich_reload "$P" "$S")" || fail "reload failed (missing backlog pane)"
grep -q "pane split pA --direction right" "$S/log" || fail "missing backlog pane did not split the coordinator pane"
grep -q "pane swap --source-pane" "$S/log" || fail "recreated backlog pane was not swapped into the left slot"
printf '%s' "$out" | grep -q "recreated ✓" || fail "recreated backlog pane not verified/reported"
ok

# ── 16. verify-failure without a detached watcher → loud warning, fallback suppressed ─
P="$T/p16"; mkdir "$P"
_make_project "$P" "reloadtest"
S="$T/state16"; _rich_coord_state "$S"
touch "$S/panes/pW/noshow"     # pane run never becomes visible, and nothing grabs the lock
out="$(_rich_reload "$P" "$S")" || fail "reload failed (verify-failure test)"
printf '%s' "$out" | grep -q "NOT relaunched" || fail "suppressed fallback not reported after verify failure"
ok

# ═══ pane registry path (tests 17+) ══════════════════════════════════════════
# coordinator.sh writes $WORKTREES_DIR/.herd-panes on creation; reload reads it to
# refresh panes in-place rather than always creating standalone tabs.

# ── 17. registry panes used in-place; no neighbor query issued ───────────────
# Pre-populate .herd-panes pointing to pW_r (watch) and pL_r (backlog) — panes
# that differ from the neighbor-derived pW/pL. If reload reads the registry, it
# runs the scripts in pW_r / pL_r and never queries pane neighbor at all.
P="$T/p17"; mkdir "$P"
_make_project "$P" "reloadtest"
S="$T/state17"; _rich_coord_state "$S"
# Create the registry-specified panes as BARE panes in the stub.
mkdir -p "$S/panes/pW_r" "$S/panes/pL_r"
P17_REAL="$(cd "$P" && pwd -P)"
cat > "$P17_REAL/trees/.herd-panes" <<REG
coordinator-agent pA tC
backlog pL_r tC
watch pW_r tC
REG
out="$(_rich_reload "$P" "$S")" || fail "reload failed (registry in-place test)"
grep -q "pane run pW_r" "$S/log" || fail "watch script not run in registry-specified watch pane"
grep -q "pane run pL_r" "$S/log" || fail "backlog script not run in registry-specified backlog pane"
grep -q "pane neighbor" "$S/log" && fail "neighbor query issued when registry panes were usable" || true
ok

# ── 18. registry watch pane GONE → falls back to neighbor/split; backlog from registry ─
# The watch pane in the registry no longer exists (pane dir absent = GONE); the
# registered backlog pane (pL_r) still exists and should be used without a neighbor query.
P="$T/p18"; mkdir "$P"
_make_project "$P" "reloadtest"
S="$T/state18"; _rich_coord_state "$S"
mkdir -p "$S/panes/pL_r"   # pW_gone intentionally absent — GONE
P18_REAL="$(cd "$P" && pwd -P)"
cat > "$P18_REAL/trees/.herd-panes" <<REG
coordinator-agent pA tC
backlog pL_r tC
watch pW_gone tC
REG
out="$(_rich_reload "$P" "$S")" || fail "reload failed (registry watch pane gone)"
# pW_gone is GONE → reload falls through to neighbor (pA.down=pW) or splits; either way
# the watch ends up in the coordinator tab.
printf '%s' "$out" | grep -q "pane below coordinator" \
  || fail "watch not placed in coordinator tab after registry pane was gone"
# backlog from registry (pL_r) used without a neighbor query.
grep -q "pane run pL_r" "$S/log" \
  || fail "backlog not run in registry pane when registry backlog pane was still valid"
ok

# ── 19. coordinator tab gone with registry present → standalone tabs ──────────
# The registry exists but the coordinator tab no longer appears in herdr tab list.
# Reload must fall through to standalone tabs (no coordinator to anchor to).
P="$T/p19"; mkdir "$P"
_make_project "$P" "reloadtest"
S="$T/state19"
mkdir -p "$S/tabs" "$S/panes" "$S/neighbors"
# No coordinator tab in state; agent list is empty → agent_pane lookup fails.
printf '{"result":{"agents":[]}}\n' > "$S/agents.json"
P19_REAL="$(cd "$P" && pwd -P)"
mkdir -p "$S/panes/pW_r" "$S/panes/pL_r"
cat > "$P19_REAL/trees/.herd-panes" <<REG
coordinator-agent pA tC
backlog pL_r tC
watch pW_r tC
REG
out="$(_rich_reload "$P" "$S")" || fail "reload failed (coordinator tab gone)"
printf '%s' "$out" | grep -q "herdr tab watch-reloadtest" \
  || fail "expected standalone watch tab when coordinator tab is gone"
ok

# ── 20. pid in summary comes from lockfile, not transient process-info ────────
# FAKE_RUN_WRITES_LOCK makes the stub write a specific pid to the lockfile during
# pane run. The summary must show that pid — not the 5151 returned by process-info —
# confirming the fix for the transient-fork-pid bug.
P="$T/p20"; mkdir "$P"
_make_project "$P" "reloadtest"
S="$T/state20"; _rich_coord_state "$S"
P20_REAL="$(cd "$P" && pwd -P)"
lockfile="$P20_REAL/trees/.watcher-reloadtest.pid"
FAKE_PID="55555"
out="$(_rich_reload "$P" "$S" FAKE_RUN_WRITES_LOCK="$lockfile:$FAKE_PID")" \
  || fail "reload failed (lockfile pid test)"
printf '%s' "$out" | grep -q "pid $FAKE_PID" \
  || fail "summary pid should come from lockfile (expected pid $FAKE_PID, got: $(printf '%s' "$out" | grep pid || echo none))"
ok

echo "ALL PASS ($pass checks)"
