#!/usr/bin/env bash
# test-driver-abstraction.sh — hermetic proof for PHASE 2 of the renderable-coordinator driver
# abstraction (docs/driver-abstraction.md): a driver DEFINITION file + render-time {{DRIVER_*}} token
# substitution in bin/herd's render_skill(), selected by the HERD_DRIVER config key (default
# herdr-claude).
#
# The CRITICAL INVARIANT this locks in: with HERD_DRIVER unset/default the rendered coordinator skill
# is FUNCTIONALLY IDENTICAL to before the abstraction — the key driver incantations appear verbatim
# and NO {{...}} token survives unsubstituted. This render-equivalence check is the safety rail for a
# change that alters how the coordinator's OWN seat renders.
#
# Also covered: the loud failure modes the design requires — an unknown HERD_DRIVER (lists the drivers
# that ship) and a driver missing a tokenized capability (an unrendered {{DRIVER_*}} token, caught by
# the completeness lint) — and a mechanical swap to a COMPLETE alternate driver.
#
# Fully hermetic: local temp git repos only. NO herdr, NO gh, NO claude, NO network, NO model.
# Run:  bash tests/test-driver-abstraction.sh
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$HERE/.." && pwd)"
HERD="$ROOT/bin/herd"
DRIVER_FILE="$ROOT/templates/drivers/herdr-claude.driver"
CAPS="$ROOT/templates/capabilities.tsv"
CFG_EXAMPLE="$ROOT/templates/config.example"

T="$(mktemp -d)"; trap 'rm -rf "$T"' EXIT
pass=0
fail(){ echo "FAIL: $1" >&2; exit 1; }
ok(){ pass=$((pass+1)); }

for f in "$HERD" "$DRIVER_FILE" "$CAPS" "$CFG_EXAMPLE"; do
  [ -f "$f" ] || fail "missing required file: $f"
done

# seed_repo <dir> [extra .herd/config lines] — a minimal herd project that `herd render` accepts.
seed_repo() {
  local d="$1" extra="${2:-}"
  git -C "$d" init -q
  git -C "$d" config user.email t@t.t; git -C "$d" config user.name t
  ( cd "$d" && git commit -q --allow-empty -m init )
  mkdir -p "$d/.herd"
  cat > "$d/.herd/config" <<EOF
HERD_VERSION=1
WORKSPACE_NAME="herdkit"
PROJECT_ROOT="$d"
DEFAULT_BRANCH="origin/main"
BACKLOG_FILE="BACKLOG.md"
SCRIBE_BACKEND="file"
HERD_REPO="briankeegan1/herdkit"
COORDINATOR_CMD="/coordinator"
$extra
EOF
}
render(){ local d="$1"; shift; ( cd "$d" && env "$@" bash "$HERD" render ); }  # render <dir> [ENV=v ...]

# ── 0. The shipped default driver binds every capability the design's model names. ────────────────
for key in DRIVER_LIST_AGENTS DRIVER_FOCUS_AGENT DRIVER_SEND_TEXT DRIVER_SWITCH_MODEL \
           DRIVER_START_AGENT DRIVER_CREATE_TAB DRIVER_READ_PANE DRIVER_SEND_KEYS; do
  grep -qE "^$key=" "$DRIVER_FILE" || fail "herdr-claude.driver missing capability binding: $key"
done
# The driver file is ZERO-SECRET / command-shapes only — the DRIVER_* VALUES carry no absolute paths
# or credential-shaped material (comments are prose and exempt; only the bindings ship into renders).
if grep -E '^DRIVER_[A-Z_]+=' "$DRIVER_FILE" | grep -qiE '/users/|/home/|secret|password|apikey'; then
  fail "a driver binding value leaks a secret or absolute path"
fi
ok; echo "PASS (0) herdr-claude.driver binds all 8 capabilities, zero-secret"

# ── 1. Default render (HERD_DRIVER unset): the INVARIANT — incantations verbatim, no leftover token.
P="$T/default"; mkdir -p "$P"; seed_repo "$P"
render "$P" >/dev/null || fail "default render failed"
SK="$P/.claude/commands/coordinator.md"
[ -f "$SK" ] || fail "default render produced no skill"

# 1a. render contract intact: not a single {{TOKEN}} survives (the render-diff-style lint).
grep -qE '\{\{' "$SK" && fail "default skill has an unsubstituted {{token}}" || true
# 1b. the GENERATED-BY header is preserved (rendering contract unchanged).
grep -q "GENERATED BY herdkit — DO NOT HAND-EDIT" "$SK" || fail "default skill lost the GENERATED-BY header"
# 1c. the four driver incantations appear EXACTLY as before the abstraction (byte-for-byte).
grep -qF 'herdr agent list' "$SK"                                            || fail "list-agents incantation changed"
grep -qF 'herdr agent focus <slug>' "$SK"                                    || fail "focus-agent incantation changed"
grep -qF 'herdr pane run <agent-pane> "<text>"; herdr pane send-keys <agent-pane> Enter' "$SK" \
  || fail "send-text incantation changed (HERD-186: must type + send-keys Enter)"
grep -qF 'herdr pane run <builder-agent-pane> "/model <MODEL_FEATURE value>"' "$SK" || fail "switch-model incantation changed"
# 1d. …and the runtime-INDEPENDENT incantations the task calls out are untouched.
grep -qE '/scribe\.sh "Mark'    "$SK" || fail "scribe.sh enqueue incantation changed"
grep -qE '/herd-quick\.sh <slug>' "$SK" || fail "herd-quick.sh spawn incantation changed"
# 1e. the phase-1 driver surface is still greppable (markers + single-source section preserved).
grep -q "## Driver commands (herdr + Claude Code)" "$SK" || fail "lost the Driver commands section"
for cap in list-agents focus-agent send-text switch-model; do
  grep -q "DRIVER:$cap" "$SK" || fail "lost DRIVER:$cap marker"
done
ok; echo "PASS (1) default render: incantations verbatim, zero leftover tokens, surface intact"

# ── 2. Setting HERD_DRIVER=herdr-claude explicitly is byte-identical to leaving it unset. ─────────
Q="$T/explicit"; mkdir -p "$Q"; seed_repo "$Q" 'HERD_DRIVER="herdr-claude"'
render "$Q" >/dev/null || fail "explicit-default render failed"
# normalize the only legitimate difference (PROJECT_ROOT path) before comparing.
sed "s#$P#PROOT#g" "$SK" > "$T/a"
sed "s#$Q#PROOT#g" "$Q/.claude/commands/coordinator.md" > "$T/b"
diff -q "$T/a" "$T/b" >/dev/null || { echo "--- unset vs explicit differ ---"; diff "$T/a" "$T/b" | head; fail "explicit herdr-claude not byte-identical to unset"; }
ok; echo "PASS (2) HERD_DRIVER=herdr-claude renders byte-identical to the default (unset)"

# ── 3. Unknown HERD_DRIVER fails LOUDLY and lists the drivers that ship. ──────────────────────────
U="$T/unknown"; mkdir -p "$U"; seed_repo "$U" 'HERD_DRIVER="vscode-copilot"'
if out="$(render "$U" 2>&1)"; then fail "unknown driver render should have failed but did not: $out"; fi
echo "$out" | grep -q "unknown HERD_DRIVER 'vscode-copilot'" || fail "unknown-driver error not loud: $out"
echo "$out" | grep -q "herdr-claude"                        || fail "unknown-driver error did not list herdr-claude: $out"
ok; echo "PASS (3) unknown HERD_DRIVER → loud error listing available drivers"

# ── 4. A driver missing a tokenized capability fails LOUDLY (unrendered {{DRIVER_*}} token). ──────
DD="$T/drivers"; mkdir -p "$DD"
cat > "$DD/incomplete.driver" <<'EOF'
DRIVER_LIST_AGENTS='x list'
DRIVER_FOCUS_AGENT='x focus'
DRIVER_SEND_TEXT='x send'
EOF
M="$T/missing"; mkdir -p "$M"; seed_repo "$M" 'HERD_DRIVER="incomplete"'
if out="$(render "$M" HERD_DRIVERS_DIR="$DD" 2>&1)"; then fail "incomplete driver should have failed the render: $out"; fi
echo "$out" | grep -q 'unsubstituted token'   || fail "completeness lint did not fire: $out"
echo "$out" | grep -q 'DRIVER_SWITCH_MODEL'    || fail "lint did not name the missing capability token: $out"
ok; echo "PASS (4) driver missing a tokenized capability → loud completeness-lint failure"

# ── 5. A COMPLETE alternate driver renders cleanly and mechanically SWAPS every incantation. ─────
cat > "$DD/altmux.driver" <<'EOF'
DRIVER_LIST_AGENTS='altmux ps'
DRIVER_FOCUS_AGENT='altmux go <slug>'
DRIVER_SEND_TEXT='altmux tell <pane> <text>'
DRIVER_SWITCH_MODEL='altmux model <pane> <value>'
EOF
A="$T/alt"; mkdir -p "$A"; seed_repo "$A" 'HERD_DRIVER="altmux"'
render "$A" HERD_DRIVERS_DIR="$DD" >/dev/null || fail "alternate driver render failed"
ASK="$A/.claude/commands/coordinator.md"
grep -qE '\{\{' "$ASK" && fail "alternate render left a leftover token" || true
grep -qF 'altmux ps'              "$ASK" || fail "alternate list-agents incantation not rendered"
grep -qF 'altmux model <pane> <value>' "$ASK" || fail "alternate switch-model incantation not rendered"
# the herdr binding is genuinely GONE from the tokenized sites — proving the swap is data-driven.
grep -qF 'herdr pane run <agent-pane> "<text>"' "$ASK" && fail "old herdr send-text binding survived a driver swap" || true
grep -qF 'herdr pane send-keys <agent-pane> Enter' "$ASK" && fail "old herdr send-text Enter binding survived a driver swap" || true
ok; echo "PASS (5) a complete alternate driver swaps every tokenized incantation, no fork"

# ── 6. HERD_DRIVER is documented as a config key AND in config.example (kept in sync). ────────────
awk -F'\t' '$1=="HERD_DRIVER" && $2=="config"{print $5}' "$CAPS" | grep -q '^render$' \
  || fail "HERD_DRIVER not a config key with requires=render in capabilities.tsv"
grep -qE '^HERD_DRIVER="herdr-claude"' "$CFG_EXAMPLE" \
  || fail "config.example does not document HERD_DRIVER default herdr-claude"
ok; echo "PASS (6) HERD_DRIVER documented (capabilities.tsv requires=render + config.example default)"

# ── 7. HERD-201: the builder lanes derive the spawn's permission flag from the RESOLVED runtime ─────
# driver, so a runtime-qualified MODEL ref spawns THAT runtime's approve flag — never claude's
# --dangerously-skip-permissions forced into a foreign runtime (the launch-death bug). Byte-identical
# for the native claude runtimes (herdr-claude/headless). Exercises the REAL fix path: resolve the ref
# → derive herd_driver_lane_permission_flags → compose herd_driver_agent_spawn_argv, exactly as the
# lanes do. driver.sh sourcing is side-effect-free (functions only), so this stays hermetic — no herdr,
# no claude, no model (each case sources driver.sh in a clean subshell to pin the env precisely).
# lane_argv <model-ref> — mirror the builder lane: resolve the (driver,model), derive the permission
# flags from the RESOLVED driver (HERD_CLAUDE_FLAGS honored exactly as the lane does), compose the spawn
# argv, and echo it space-joined for a stable string compare.
lane_argv() {
  local ref="$1" mdl drv flags
  mdl="$(herd_model_for_spawn "$ref")" || return 1
  drv="$(herd_model_driver_for "$ref" 2>/dev/null || true)"; [ -n "$drv" ] || drv="$(herd_driver_name)"
  flags="$(herd_driver_lane_permission_flags "$drv")"
  local -a a=(); local t
  while IFS= read -r -d '' t; do a+=("$t"); done < <(herd_driver_agent_spawn_argv "$drv" "$mdl" "$flags" PTR)
  printf '%s' "${a[*]}"
}

# 7a. a grok: ref composes grok's OWN --always-approve flag — never the claude flag.
got="$(env -u HERD_CLAUDE_FLAGS -u HERD_DRIVER bash -c '. "$1"; '"$(declare -f lane_argv)"'; lane_argv grok:grok-4.5' _ "$ROOT/scripts/herd/driver.sh")"
[ "$got" = "grok --model grok-4.5 --always-approve PTR" ] \
  || fail "grok ref did not compose grok's permission flag: got [$got]"
case "$got" in *--dangerously-skip-permissions*) fail "grok spawn leaked the claude permission flag: $got" ;; esac
# 7b. a codex: ref composes codex's OWN bypass flag — never the claude flag.
got="$(env -u HERD_CLAUDE_FLAGS -u HERD_DRIVER bash -c '. "$1"; '"$(declare -f lane_argv)"'; lane_argv codex:gpt-5-codex' _ "$ROOT/scripts/herd/driver.sh")"
[ "$got" = "codex --model gpt-5-codex --dangerously-bypass-approvals-and-sandbox PTR" ] \
  || fail "codex ref did not compose codex's permission flag: got [$got]"
case "$got" in *--dangerously-skip-permissions*) fail "codex spawn leaked the claude permission flag: $got" ;; esac
# 7c. the native claude runtimes stay BYTE-IDENTICAL (bare ref → default driver; explicit headless ref).
got="$(env -u HERD_CLAUDE_FLAGS -u HERD_DRIVER bash -c '. "$1"; '"$(declare -f lane_argv)"'; lane_argv opus' _ "$ROOT/scripts/herd/driver.sh")"
[ "$got" = "claude --model opus --dangerously-skip-permissions PTR" ] \
  || fail "bare model ref not byte-identical (native claude): got [$got]"
got="$(env -u HERD_CLAUDE_FLAGS -u HERD_DRIVER bash -c '. "$1"; '"$(declare -f lane_argv)"'; lane_argv headless:sonnet' _ "$ROOT/scripts/herd/driver.sh")"
[ "$got" = "claude --model sonnet --dangerously-skip-permissions PTR" ] \
  || fail "headless ref not byte-identical (native claude): got [$got]"
# 7d. an EXPLICIT HERD_CLAUDE_FLAGS override still WINS — verbatim, even for a foreign runtime.
got="$(env -u HERD_DRIVER HERD_CLAUDE_FLAGS='--custom-yolo' bash -c '. "$1"; '"$(declare -f lane_argv)"'; lane_argv grok:grok-4.5' _ "$ROOT/scripts/herd/driver.sh")"
[ "$got" = "grok --model grok-4.5 --custom-yolo PTR" ] \
  || fail "explicit HERD_CLAUDE_FLAGS override did not win for a grok ref: got [$got]"
ok; echo "PASS (7) HERD-201: lanes derive the permission flag from the resolved runtime (grok/codex own flag; claude byte-identical; explicit override wins)"

echo "ALL PASS ($pass checks)"
