#!/usr/bin/env bash
# test-cli-reload.sh — hermetic tests for `herd reload`.
#
# Uses HERD_RELOAD_SKIP_LAUNCH=1 to suppress the background watcher launch so tests do
# not leave persistent background processes in CI/test environments.
#
# Tests (no network, no herdr, no real watcher):
#   1. reload renders the coordinator skill from updated .herd/config
#   2. reload prints the effective MERGE_POLICY (explicit and derived cases)
#   3. reload removes the lockfile (non-existent PID is harmless)
#   4. reload kills a live process recorded in the lockfile
#   5. reload is a no-op kill when there is no lockfile
#   6. reload fails with a clear error when .herd/config is absent
#
# Run:  bash tests/test-cli-reload.sh
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
HERD="$HERE/../bin/herd"

T="$(mktemp -d)"; trap 'rm -rf "$T"' EXIT
fail(){ echo "FAIL: $1" >&2; exit 1; }
pass=0
ok(){ pass=$((pass+1)); }

# _make_project ROOT WORKSPACE [extra config lines...]
_make_project() {
  local r="$1" ws="$2"; shift 2
  git -C "$r" init -q
  git -C "$r" config user.email t@t.t; git -C "$r" config user.name t
  ( cd "$r" && git commit -q --allow-empty -m init )
  mkdir -p "$r/.herd" "$r/trees"
  cat > "$r/.herd/config" <<CFG
HERD_VERSION=1
PROJECT_ROOT="$r"
WORKTREES_DIR="$r/trees"
DEFAULT_BRANCH="origin/main"
WORKSPACE_NAME="$ws"
BACKLOG_FILE="BACKLOG.md"
SCRIBE_BACKEND="file"
WATCHER_AUTOMERGE="true"
CFG
  for line in "$@"; do printf '%s\n' "$line" >> "$r/.herd/config"; done
}

# ── 1. reload renders the coordinator skill ───────────────────────────────────
P="$T/p1"; mkdir "$P"
_make_project "$P" "reloadtest"
( cd "$P" && HERD_RELOAD_SKIP_LAUNCH=1 bash "$HERD" reload >/dev/null 2>&1 ) \
  || fail "reload failed (basic run)"
[ -f "$P/.claude/commands/coordinator.md" ] || fail "reload did not render coordinator skill"
grep -q "GENERATED BY herdkit" "$P/.claude/commands/coordinator.md" \
  || fail "rendered skill missing generated banner"
grep -q '{{' "$P/.claude/commands/coordinator.md" \
  && fail "rendered skill has unrendered {{tokens}}" || true
ok

# ── 2a. MERGE_POLICY=auto is printed ─────────────────────────────────────────
P="$T/p2a"; mkdir "$P"
_make_project "$P" "reloadtest" 'MERGE_POLICY="auto"'
out="$( cd "$P" && HERD_RELOAD_SKIP_LAUNCH=1 bash "$HERD" reload 2>&1 )"
printf '%s' "$out" | grep -q "MERGE_POLICY:" || fail "output missing MERGE_POLICY line"
printf '%s' "$out" | grep -q "auto"          || fail "MERGE_POLICY should be 'auto'"
ok

# ── 2b. MERGE_POLICY=approve is printed ──────────────────────────────────────
P="$T/p2b"; mkdir "$P"
_make_project "$P" "reloadtest" 'MERGE_POLICY="approve"'
out="$( cd "$P" && HERD_RELOAD_SKIP_LAUNCH=1 bash "$HERD" reload 2>&1 )"
printf '%s' "$out" | grep -q "approve" || fail "MERGE_POLICY should be 'approve'"
ok

# ── 2c. MERGE_POLICY=observe is printed ──────────────────────────────────────
P="$T/p2c"; mkdir "$P"
_make_project "$P" "reloadtest" 'MERGE_POLICY="observe"'
out="$( cd "$P" && HERD_RELOAD_SKIP_LAUNCH=1 bash "$HERD" reload 2>&1 )"
printf '%s' "$out" | grep -q "observe" || fail "MERGE_POLICY should be 'observe'"
ok

# ── 2d. WATCHER_AUTOMERGE=false derives approve when MERGE_POLICY is unset ───
P="$T/p2d"; mkdir "$P"
_make_project "$P" "reloadtest" 'WATCHER_AUTOMERGE="false"'
out="$( cd "$P" && HERD_RELOAD_SKIP_LAUNCH=1 bash "$HERD" reload 2>&1 )"
printf '%s' "$out" | grep -q "approve" || fail "WATCHER_AUTOMERGE=false should derive approve"
ok

# ── 2e. Default (WATCHER_AUTOMERGE=true, no MERGE_POLICY) derives auto ───────
P="$T/p2e"; mkdir "$P"
_make_project "$P" "reloadtest"
out="$( cd "$P" && HERD_RELOAD_SKIP_LAUNCH=1 bash "$HERD" reload 2>&1 )"
printf '%s' "$out" | grep -q "auto" || fail "default WATCHER_AUTOMERGE=true should derive auto"
ok

# ── 3. reload removes lockfile with a non-existent PID ───────────────────────
P="$T/p3"; mkdir "$P"
_make_project "$P" "reloadtest"
lockfile="$P/trees/.watcher-reloadtest.pid"
printf '%s\n' "99999999" > "$lockfile"   # almost certainly a non-existent PID
( cd "$P" && HERD_RELOAD_SKIP_LAUNCH=1 bash "$HERD" reload >/dev/null 2>&1 ) \
  || fail "reload failed with dead-PID lockfile"
[ -f "$lockfile" ] && fail "reload did not remove the lockfile" || true
ok

# ── 4. reload kills a live process recorded in the lockfile ───────────────────
P="$T/p4"; mkdir "$P"
_make_project "$P" "reloadtest"
lockfile="$P/trees/.watcher-reloadtest.pid"
sleep 999 &
FAKEPID=$!
printf '%s\n' "$FAKEPID" > "$lockfile"
( cd "$P" && HERD_RELOAD_SKIP_LAUNCH=1 bash "$HERD" reload >/dev/null 2>&1 ) \
  || { kill "$FAKEPID" 2>/dev/null || true; fail "reload failed when a live PID was in lockfile"; }
sleep 0.3
kill -0 "$FAKEPID" 2>/dev/null \
  && { kill "$FAKEPID" 2>/dev/null || true; fail "reload did not kill the fake watcher (PID $FAKEPID)"; } \
  || true
[ -f "$lockfile" ] && fail "reload did not remove the lockfile after killing watcher" || true
ok

# ── 5. reload notes no running watcher when lockfile is absent ───────────────
P="$T/p5"; mkdir "$P"
_make_project "$P" "reloadtest"
out="$( cd "$P" && HERD_RELOAD_SKIP_LAUNCH=1 bash "$HERD" reload 2>&1 )"
printf '%s' "$out" | grep -qi "no running watcher\|not found" \
  || fail "reload should note no running watcher when lockfile is absent"
ok

# ── 6. reload fails clearly with no .herd/config ─────────────────────────────
P="$T/p6"; mkdir "$P"
git -C "$P" init -q; git -C "$P" config user.email t@t.t; git -C "$P" config user.name t
( cd "$P" && git commit -q --allow-empty -m init )
out="$( cd "$P" && HERD_RELOAD_SKIP_LAUNCH=1 bash "$HERD" reload 2>&1 || true )"
printf '%s' "$out" | grep -qi "herd init\|no .herd/config" \
  || fail "reload should report missing .herd/config clearly"
ok

echo "ALL PASS ($pass checks)"
