#!/usr/bin/env bash
# test-headless-driver.sh — hermetic proof for the HEADLESS driver (HERD-7): the second shipped
# driver, whose principle is "panes become a VIEW, not a dependency". The watcher + journal +
# notifications + limit detection must run with NO herdr panes, fail-soft, and the default
# herdr-claude driver must stay byte-identical.
#
# Covers:
#   0. templates/drivers/headless.driver binds all 8 capabilities, zero-secret.
#   1. HERD_DRIVER=headless renders the coordinator skill cleanly (no leftover tokens; headless
#      incantations swapped in; GENERATED-BY header preserved).
#   2. The unknown-driver error now lists BOTH shipped drivers (herdr-claude AND headless).
#   3. scripts/herd/driver.sh under HERD_DRIVER=headless: every capability fail-soft, with real
#      registry/log/notification-sink behavior and documented no-ops.
#   4. scripts/herd/driver.sh under HERD_DRIVER=herdr-claude delegates to the EXACT herdr command
#      it replaces (byte-identical default), proven against a stub herdr on PATH.
#   5. THE STRUCTURAL FIX: dead-builder reconciliation does NOT falsely reap under headless — a live
#      registry agent reads as ALIVE (liveness from the registry, not `herdr agent list`), while a
#      genuinely-absent agent still crosses to DEAD.
#
# Fully hermetic: local temp dirs + a stub herdr/claude on PATH. NO real herdr, NO claude, NO gh,
# NO network, NO model. Run:  bash tests/test-headless-driver.sh
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$HERE/.." && pwd)"
HERD="$ROOT/bin/herd"
DRIVER_SH="$ROOT/scripts/herd/driver.sh"
HEADLESS_DRIVER="$ROOT/templates/drivers/headless.driver"
WATCH="$ROOT/scripts/herd/agent-watch.sh"

T="$(mktemp -d)"; trap 'rm -rf "$T"' EXIT
pass=0
fail(){ echo "FAIL: $1" >&2; exit 1; }
ok(){ pass=$((pass+1)); }

for f in "$HERD" "$DRIVER_SH" "$HEADLESS_DRIVER" "$WATCH"; do
  [ -f "$f" ] || fail "missing required file: $f"
done

seed_repo() {
  local d="$1" extra="${2:-}"
  git -C "$d" init -q
  git -C "$d" config user.email t@t.t; git -C "$d" config user.name t
  ( cd "$d" && git commit -q --allow-empty -m init )
  mkdir -p "$d/.herd"
  cat > "$d/.herd/config" <<EOF
HERD_VERSION=1
WORKSPACE_NAME="herdkit"
PROJECT_ROOT="$d"
DEFAULT_BRANCH="origin/main"
BACKLOG_FILE="BACKLOG.md"
SCRIBE_BACKEND="file"
HERD_REPO="briankeegan1/herdkit"
COORDINATOR_CMD="/coordinator"
$extra
EOF
}
render(){ local d="$1"; shift; ( cd "$d" && env "$@" bash "$HERD" render ); }

# ── 0. headless.driver binds every capability, zero-secret. ──────────────────────────────────────
for key in DRIVER_LIST_AGENTS DRIVER_FOCUS_AGENT DRIVER_SEND_TEXT DRIVER_SWITCH_MODEL \
           DRIVER_START_AGENT DRIVER_CREATE_TAB DRIVER_READ_PANE DRIVER_SEND_KEYS; do
  grep -qE "^$key=" "$HEADLESS_DRIVER" || fail "headless.driver missing capability binding: $key"
done
if grep -E '^DRIVER_[A-Z_]+=' "$HEADLESS_DRIVER" | grep -qiE '/users/|/home/|secret|password|apikey'; then
  fail "a headless.driver binding value leaks a secret or absolute path"
fi
ok; echo "PASS (0) headless.driver binds all 8 capabilities, zero-secret"

# ── 1. HERD_DRIVER=headless renders cleanly. ──────────────────────────────────────────────────────
P="$T/headless"; mkdir -p "$P"; seed_repo "$P" 'HERD_DRIVER="headless"'
render "$P" >/dev/null || fail "headless render failed"
SK="$P/.claude/commands/coordinator.md"
[ -f "$SK" ] || fail "headless render produced no skill"
grep -qE '\{\{' "$SK" && fail "headless skill has an unsubstituted {{token}}" || true
grep -q "GENERATED BY herdkit — DO NOT HAND-EDIT" "$SK" || fail "headless skill lost the GENERATED-BY header"
# Only the four INLINE capabilities are tokenized into the skill (list/focus/send-text/switch-model);
# read-pane/send-keys/create-tab/start-agent live in the driver file for the lanes + watcher.
grep -qF 'driver.sh list-agents'          "$SK" || fail "headless list-agents incantation not rendered"
grep -qF 'driver.sh send-text'            "$SK" || fail "headless send-text incantation not rendered"
grep -qF 'driver.sh focus'                "$SK" || fail "headless focus-agent incantation not rendered"
# the herdr binding is genuinely GONE from the tokenized send-text site (proves the swap is real).
grep -qF 'herdr pane run <agent-pane> "<text>"' "$SK" && fail "old herdr send-text binding survived headless" || true
ok; echo "PASS (1) HERD_DRIVER=headless renders cleanly, headless incantations swapped in"

# ── 2. Unknown driver error lists BOTH shipped drivers. ──────────────────────────────────────────
U="$T/unknown"; mkdir -p "$U"; seed_repo "$U" 'HERD_DRIVER="vscode-copilot"'
if out="$(render "$U" 2>&1)"; then fail "unknown driver render should have failed: $out"; fi
echo "$out" | grep -q "herdr-claude" || fail "unknown-driver error did not list herdr-claude: $out"
echo "$out" | grep -q "headless"     || fail "unknown-driver error did not list headless: $out"
ok; echo "PASS (2) unknown driver → loud error listing herdr-claude AND headless"

# ── 3. driver.sh under HERD_DRIVER=headless — fail-soft capabilities. ─────────────────────────────
( set +e
  export HERD_DRIVER="headless" WORKTREES_DIR="$T/proj" HERD_HEADLESS_NATIVE_NOTIFY=off
  mkdir -p "$WORKTREES_DIR/.herd"
  # shellcheck source=/dev/null
  . "$DRIVER_SH"
  [ "$(herd_driver_name)" = "headless" ] || { echo "FAIL: driver name not headless"; exit 1; }

  # list-agents: empty registry → an empty roster (never a broken parse).
  j="$(herd_driver_agent_list_json)"
  echo "$j" | grep -qF '"agents":[]' || { echo "FAIL: empty registry not empty roster: $j"; exit 1; }

  # seed a LIVE agent (this test's pid) + a DEAD one (a pid that cannot exist).
  mkdir -p "$WORKTREES_DIR/.herd/agents/live" "$WORKTREES_DIR/.herd/agents/gone"
  echo $$ > "$WORKTREES_DIR/.herd/agents/live/pid"; echo working > "$WORKTREES_DIR/.herd/agents/live/status"
  echo 2147483646 > "$WORKTREES_DIR/.herd/agents/gone/pid"
  j="$(herd_driver_agent_list_json)"
  echo "$j" | grep -qF '"name":"live"' || { echo "FAIL: live agent not listed: $j"; exit 1; }
  echo "$j" | grep -qF '"name":"gone"' && { echo "FAIL: dead-pid agent WAS listed: $j"; exit 1; }

  # notify: durable sink written, rc 0.
  herd_driver_notify "🐑 t" "the body" default || { echo "FAIL: notify rc"; exit 1; }
  grep -qF "the body" "$WORKTREES_DIR/.herd/notifications.log" || { echo "FAIL: notify sink not written"; exit 1; }

  # no-ops: rc 0, never touch herdr.
  herd_driver_send_keys somepane Down Enter || { echo "FAIL: send-keys rc"; exit 1; }
  herd_driver_create_tab --workspace x     || { echo "FAIL: create-tab rc"; exit 1; }
  herd_driver_close_pane somepane          || { echo "FAIL: close-pane rc"; exit 1; }
  # pane-alive: headless has no panes → always NOT alive (liveness there is the registry pid).
  herd_driver_pane_alive somepane          && { echo "FAIL: headless pane-alive should be false"; exit 1; }

  # read-pane: empty on no log, tails a real log.
  [ -z "$(herd_driver_read_pane nosuch)" ] || { echo "FAIL: read-pane not empty for missing agent"; exit 1; }
  printf 'hello-log\n' > "$WORKTREES_DIR/.herd/agents/live/log"
  herd_driver_read_pane live | grep -qF hello-log || { echo "FAIL: read-pane did not tail the log"; exit 1; }

  # send-text: queues to the input file.
  herd_driver_send_text live "wake up" || { echo "FAIL: send-text rc"; exit 1; }
  grep -qF "wake up" "$WORKTREES_DIR/.herd/agents/live/input" || { echo "FAIL: send-text not queued"; exit 1; }

  # focus: prints view guidance, rc 0.
  herd_driver_focus_agent live | grep -qF "tail -f" || { echo "FAIL: focus did not print view guidance"; exit 1; }
  exit 0
) || fail "headless capability checks failed (see FAIL above)"
ok; echo "PASS (3) headless driver: registry liveness, notify sink, no-ops, log tail — all fail-soft"

# ── 4. driver.sh under HERD_DRIVER=herdr-claude delegates byte-identically. ───────────────────────
BIN="$T/bin"; mkdir -p "$BIN"
cat > "$BIN/herdr" <<'STUB'
#!/usr/bin/env bash
{ printf 'HERDR:'; for a in "$@"; do printf ' [%s]' "$a"; done; printf '\n'; } >> "$HERDR_LOG"
[ "$1" = "agent" ] && [ "$2" = "list" ] && echo '{"result":{"agents":[{"name":"x","agent_status":"working"}]}}'
exit 0
STUB
chmod +x "$BIN/herdr"
( set +e
  export HERD_DRIVER="herdr-claude" PATH="$BIN:$PATH" HERDR_LOG="$T/herdr.log"
  : > "$HERDR_LOG"
  # shellcheck source=/dev/null
  . "$DRIVER_SH"
  herd_driver_notify "🐑 title" "the body" default
  herd_driver_agent_list_json >/dev/null
  herd_driver_read_pane "%p1" visible >/dev/null
  herd_driver_send_keys "%p2" Down Enter
  herd_driver_close_pane "%p3"
  herd_driver_pane_alive "%p4" >/dev/null
  grep -qF 'HERDR: [notification] [show] [🐑 title] [--body] [the body] [--sound] [default]' "$HERDR_LOG" || { echo "FAIL: notify not byte-identical"; cat "$HERDR_LOG"; exit 1; }
  grep -qF 'HERDR: [agent] [list]' "$HERDR_LOG" || { echo "FAIL: agent list not delegated"; exit 1; }
  grep -qF 'HERDR: [pane] [read] [%p1] [--source] [visible]' "$HERDR_LOG" || { echo "FAIL: read-pane not byte-identical"; cat "$HERDR_LOG"; exit 1; }
  grep -qF 'HERDR: [pane] [send-keys] [%p2] [Down] [Enter]' "$HERDR_LOG" || { echo "FAIL: send-keys not byte-identical"; cat "$HERDR_LOG"; exit 1; }
  grep -qF 'HERDR: [pane] [close] [%p3]' "$HERDR_LOG" || { echo "FAIL: close-pane not byte-identical"; cat "$HERDR_LOG"; exit 1; }
  grep -qF 'HERDR: [pane] [read] [%p4]' "$HERDR_LOG" || { echo "FAIL: pane-alive not delegated to pane read"; cat "$HERDR_LOG"; exit 1; }
  exit 0
) || fail "herdr-claude delegation not byte-identical (see FAIL above)"
ok; echo "PASS (4) herdr-claude driver delegates to the EXACT herdr command (byte-identical default)"

# ── 5. Dead-builder reconciliation: NO false reap under headless. ─────────────────────────────────
# The watcher sources driver.sh; confirm, then prove liveness comes from the registry.
grep -qE '^\. "\$HERE/driver\.sh"' "$WATCH" || fail "agent-watch.sh does not source driver.sh"
( set +e
  export AGENT_WATCH_LIB=1 HERD_CONFIG_FILE="$T/no-such-config" HERD_DRIVER="headless"
  # shellcheck source=/dev/null
  . "$WATCH" || { echo "FAIL: sourcing agent-watch.sh (lib mode) failed"; exit 1; }
  type _classify_dead_builder >/dev/null 2>&1 || { echo "FAIL: _classify_dead_builder not defined"; exit 1; }
  export WORKTREES_DIR="$T/proj2"
  mkdir -p "$WORKTREES_DIR/.herd/agents/builder-a"
  echo $$ > "$WORKTREES_DIR/.herd/agents/builder-a/pid"; echo working > "$WORKTREES_DIR/.herd/agents/builder-a/status"

  # The watcher builds ag_status from herd_driver_agent_list_json exactly as its tick does.
  astatus="$(herd_driver_agent_list_json | AG=builder-a python3 -c '
import os,sys,json
j=json.load(sys.stdin); ags=(j.get("result") or {}).get("agents") or []
m={a.get("name"):a.get("agent_status") for a in ags if a.get("name")}
sys.stdout.write(m.get(os.environ["AG"],""))')"
  [ "$astatus" = "working" ] || { echo "FAIL: live registry agent has no status ('$astatus')"; exit 1; }
  # has_agent=1 (astatus non-empty) ⇒ ALIVE, never reaped, even past the grace window.
  v="$(_classify_dead_builder 1 0 no 100 100000 120)"
  [ "$v" = "ALIVE" ] || { echo "FAIL: live headless agent classified $v, expected ALIVE"; exit 1; }
  # A genuinely-absent agent (no registry entry ⇒ has_agent=0) still crosses to DEAD past grace.
  v="$(_classify_dead_builder 0 0 no 100 100000 120)"
  [ "$v" = "DEAD" ] || { echo "FAIL: absent agent classified $v, expected DEAD"; exit 1; }
  exit 0
) || fail "headless dead-builder reconciliation checks failed (see FAIL above)"
ok; echo "PASS (5) headless: live registry agent reads ALIVE (no false reap); absent agent still DEAD"

echo "ALL PASS ($pass checks)"
